"""initial schema

Revision ID: d3a89b915dbe
Revises: 
Create Date: 2026-07-14 10:44:03.917812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a89b915dbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary_multiplier', sa.Float(), nullable=False),
    sa.Column('head_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['head_employee_id'], ['employees.id'], use_alter=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('turnover_probability', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('model_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.id'], use_alter=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnover_training_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('horizon_ticks', sa.Integer(), nullable=False),
    sa.Column('quit_within_horizon', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('is_manager', sa.Integer(), nullable=False),
    sa.Column('promotions_count', sa.Integer(), nullable=False),
    sa.Column('mood_pulse_mean', sa.Float(), nullable=False),
    sa.Column('stress_level_pulse_mean', sa.Float(), nullable=False),
    sa.Column('sleep_quality_pulse_mean', sa.Float(), nullable=False),
    sa.Column('energy_level_pulse_mean', sa.Float(), nullable=False),
    sa.Column('burnout_exhaustion_pulse_mean', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('work_mode', sa.String(), nullable=False),
    sa.Column('promotions_count', sa.Integer(), nullable=False),
    sa.Column('productivity', sa.Float(), nullable=False),
    sa.Column('engagement', sa.Float(), nullable=False),
    sa.Column('collaboration', sa.Float(), nullable=False),
    sa.Column('turnover_risk', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_wellbeing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('openness', sa.Float(), nullable=False),
    sa.Column('conscientiousness', sa.Float(), nullable=False),
    sa.Column('extraversion', sa.Float(), nullable=False),
    sa.Column('agreeableness', sa.Float(), nullable=False),
    sa.Column('neuroticism', sa.Float(), nullable=False),
    sa.Column('education_level', sa.String(), nullable=False),
    sa.Column('first_gen_professional', sa.Integer(), nullable=False),
    sa.Column('childhood_ses_quintile', sa.Integer(), nullable=False),
    sa.Column('ace_score', sa.Integer(), nullable=False),
    sa.Column('attachment_style', sa.String(), nullable=False),
    sa.Column('financial_security_score', sa.Float(), nullable=False),
    sa.Column('caregiving_load', sa.Float(), nullable=False),
    sa.Column('commute_burden_minutes', sa.Integer(), nullable=False),
    sa.Column('hours_slept_typical', sa.Float(), nullable=False),
    sa.Column('physical_health_score', sa.Float(), nullable=False),
    sa.Column('recent_life_event', sa.String(), nullable=False),
    sa.Column('months_since_life_event', sa.Integer(), nullable=False),
    sa.Column('social_support_score', sa.Float(), nullable=False),
    sa.Column('mood', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.Float(), nullable=False),
    sa.Column('sleep_quality', sa.Float(), nullable=False),
    sa.Column('energy_level', sa.Float(), nullable=False),
    sa.Column('anxiety_symptom_score', sa.Float(), nullable=False),
    sa.Column('depression_symptom_score', sa.Float(), nullable=False),
    sa.Column('life_satisfaction', sa.Float(), nullable=False),
    sa.Column('burnout_exhaustion', sa.Float(), nullable=False),
    sa.Column('burnout_cynicism', sa.Float(), nullable=False),
    sa.Column('burnout_efficacy', sa.Float(), nullable=False),
    sa.Column('workload_perceived', sa.Float(), nullable=False),
    sa.Column('autonomy_score', sa.Float(), nullable=False),
    sa.Column('psychological_safety_perceived', sa.Float(), nullable=False),
    sa.Column('manager_support_score', sa.Float(), nullable=False),
    sa.Column('peer_support_score', sa.Float(), nullable=False),
    sa.Column('meaning_at_work_score', sa.Float(), nullable=False),
    sa.Column('growth_opportunity_score', sa.Float(), nullable=False),
    sa.Column('recognition_score', sa.Float(), nullable=False),
    sa.Column('role_clarity_score', sa.Float(), nullable=False),
    sa.Column('effort_reward_imbalance', sa.Float(), nullable=False),
    sa.Column('eap_utilization_last_year', sa.Integer(), nullable=False),
    sa.Column('mental_health_engagement', sa.String(), nullable=False),
    sa.Column('wellness_program_participation', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_wellbeing')
    op.drop_table('employees')
    op.drop_table('turnover_training_examples')
    op.drop_table('teams')
    op.drop_table('employee_risk_snapshots')
    op.drop_table('runs')
    op.drop_table('departments')
    op.drop_table('orgs')
    # ### end Alembic commands ###
