"""add performance reviews and document-derived rating features

Revision ID: eb17c27ec70e
Revises: 88ae39625708
Create Date: 2026-07-31 18:07:08.823979

Hand-adjusted from the autogenerated script in two places:

- The ``exit_note_records.source_document_id`` foreign key is added inside
  ``batch_alter_table``. SQLite has no ``ALTER TABLE ADD CONSTRAINT``, so
  the bare ``op.create_foreign_key`` autogenerate emitted would fail at
  runtime; batch mode recreates the table with the constraint instead.
  The constraint is also given an explicit name, since an unnamed one
  can't be dropped again in ``downgrade``.
- ``turnover_training_examples.rating_*`` are added NOT NULL with a
  ``server_default`` matching the constant those rows actually carried
  before ingestion existed (3.0/3.0/0.0 — see
  ``db_models.TurnoverTrainingExample``), so the backfill states a fact
  rather than guessing one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb17c27ec70e'
down_revision: Union[str, Sequence[str], None] = '88ae39625708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_EXIT_NOTE_DOC_FK = "fk_exit_note_records_source_document_id"


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'performance_reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('review_period_end', sa.Date(), nullable=False),
        sa.Column('rating', sa.Float(), nullable=False),
        sa.Column('summary_text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    with op.batch_alter_table('exit_note_records') as batch_op:
        batch_op.add_column(sa.Column('source_document_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            _EXIT_NOTE_DOC_FK, 'source_documents', ['source_document_id'], ['id'],
        )

    op.add_column(
        'turnover_training_examples',
        sa.Column('rating_last', sa.Float(), server_default='3.0', nullable=False),
    )
    op.add_column(
        'turnover_training_examples',
        sa.Column('rating_prev', sa.Float(), server_default='3.0', nullable=False),
    )
    op.add_column(
        'turnover_training_examples',
        sa.Column('rating_delta', sa.Float(), server_default='0.0', nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('turnover_training_examples', 'rating_delta')
    op.drop_column('turnover_training_examples', 'rating_prev')
    op.drop_column('turnover_training_examples', 'rating_last')

    with op.batch_alter_table('exit_note_records') as batch_op:
        batch_op.drop_constraint(_EXIT_NOTE_DOC_FK, type_='foreignkey')
        batch_op.drop_column('source_document_id')

    op.drop_table('performance_reviews')
